# Generated by Django 4.2.15 on 2024-10-18 08:05

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenieAPIKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_hash", models.CharField(max_length=255, unique=True)),
                ("key_unsafe", models.CharField(blank=True, max_length=255, null=True)),
                ("usage_limit", models.IntegerField(default=0)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "allowed_paths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=256),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "genie_api_keys",
            },
        ),
        migrations.CreateModel(
            name="GenieApprovedQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=8192, unique=True)),
                ("answer", models.CharField(blank=True, max_length=8192, null=True)),
                (
                    "chart_code",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                ("datetime", models.DateTimeField()),
                ("db_schema", models.CharField(blank=True, default="", max_length=255)),
                (
                    "db_warehouse",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "resourcename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                "db_table": "genie_approved_questions",
                "ordering": ["-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("question", models.CharField(blank=True, max_length=8192, null=True)),
                (
                    "question_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("answer", models.CharField(blank=True, max_length=8192, null=True)),
                (
                    "team_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "user_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_answered", models.BooleanField()),
                ("db_schema", models.CharField(blank=True, default="", max_length=255)),
                (
                    "db_warehouse",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "resourcename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("ai_engine", models.CharField(blank=True, max_length=32, null=True)),
                ("ai_temp", models.FloatField(blank=True, default=0, null=True)),
                ("ai_model", models.CharField(blank=True, max_length=255, null=True)),
                ("results_len", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0)),
                (
                    "ai_response",
                    models.CharField(blank=True, max_length=8192, null=True),
                ),
                (
                    "intermediate_steps",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "chart_code",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                ("chart_image_url", models.URLField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, default=0, null=True)),
                ("total_cost", models.FloatField(blank=True, default=0, null=True)),
                ("total_time", models.FloatField(blank=True, default=0, null=True)),
                ("status", models.IntegerField(blank=True, default=0, null=True)),
                ("error_msg", models.CharField(blank=True, max_length=8192, null=True)),
                ("client_type", models.FloatField(blank=True, default=0, null=True)),
                (
                    "results_s3_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "genie_chat_history",
                "ordering": ["-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieCompanies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("website", models.URLField(unique=True)),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "db_table": "genie_companies",
                "ordering": ["-website", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GeniePaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("amount", models.FloatField()),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "db_table": "genie_payment_plan",
                "ordering": ["-amount"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=64, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "database_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "team_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "user_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users",
                "ordering": ["-username", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsersPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "payment_intent",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.CharField(blank=True, max_length=16, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "subscription_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "subscription_current_period_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "subscription_current_period_end_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "subscription_item_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_payment_plan_id",
                    models.ForeignKey(
                        db_column="genie_payment_plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniepaymentplan",
                    ),
                ),
                (
                    "genie_users_id",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users_payments",
                "ordering": ["-genie_users_id", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsersDatabaseGuardrails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                ("db_schema", models.CharField(blank=True, default="", max_length=255)),
                (
                    "resourcename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "table_column",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("access_type", models.IntegerField(default=0)),
                ("datetime", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "db_warehouse",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_users",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users_db_guardrails",
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsersDatabaseConnectionDetailsDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("db_schema", models.CharField(blank=True, default="", max_length=255)),
                (
                    "db_warehouse",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "resourcename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "column_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "column_description",
                    models.CharField(blank=True, max_length=8192, null=True),
                ),
                ("column_distinct", models.JSONField(default=list)),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users_db_connection_details_column_description",
                "ordering": ["-datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsersDatabaseConnectionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("db_schema", models.CharField(blank=True, default="", max_length=255)),
                (
                    "db_warehouse",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "resourcename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("table_columns", models.JSONField(default=list)),
                ("foreign_keys", models.JSONField(default=list)),
                ("examples", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "COMPLETED"), ("FAILED", "FAILED")],
                        default="COMPLETED",
                        max_length=15,
                    ),
                ),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.CharField(blank=True, max_length=8192, null=True),
                ),
                (
                    "table_schema",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_users",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users_db_connection_details",
                "ordering": ["-datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUsersDatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("host", models.CharField(blank=True, max_length=512, null=True)),
                ("port", models.CharField(blank=True, max_length=64, null=True)),
                ("ssl", models.BooleanField(blank=True, null=True)),
                (
                    "databasename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=512, null=True)),
                ("password", models.CharField(blank=True, max_length=512, null=True)),
                ("apikey", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "resourcename",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "connection_string_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("db_type", models.CharField(blank=True, max_length=64, null=True)),
                ("is_sync", models.BooleanField(blank=True, default=False)),
                ("last_sync", models.DateTimeField(blank=True, default=False)),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_users_id",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_connections",
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_users_database_connection",
                "ordering": ["-genie_users_id", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUserLoginMagicLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                ("secret_code", models.CharField(max_length=32, unique=True)),
                ("datetime", models.DateTimeField()),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_users_id",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_user_login_magic_link",
                "ordering": ["-email", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="GenieUserInvitations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                ("secret_code", models.CharField(max_length=32, unique=True)),
                (
                    "team_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "user_id_slack",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("invite_type", models.CharField(blank=True, max_length=32, null=True)),
                ("datetime", models.DateTimeField()),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.geniecompanies",
                    ),
                ),
                (
                    "genie_users_id",
                    models.ForeignKey(
                        db_column="genie_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genie.genieusers",
                    ),
                ),
            ],
            options={
                "db_table": "genie_user_invitations",
                "ordering": ["-email", "-datetime"],
                "get_latest_by": ["datetime"],
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddIndex(
            model_name="geniepaymentplan",
            index=models.Index(fields=["plan"], name="genie_payme_plan_de6d65_idx"),
        ),
        migrations.AddIndex(
            model_name="geniecompanies",
            index=models.Index(
                fields=["website"], name="genie_compa_website_7db224_idx"
            ),
        ),
        migrations.AddField(
            model_name="geniechathistory",
            name="company_id",
            field=models.ForeignKey(
                db_column="company_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.geniecompanies",
            ),
        ),
        migrations.AddField(
            model_name="geniechathistory",
            name="genie_users_id",
            field=models.ForeignKey(
                db_column="genie_users_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.genieusers",
            ),
        ),
        migrations.AddField(
            model_name="genieapprovedquestions",
            name="approved_by",
            field=models.ForeignKey(
                db_column="approved_by",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.genieusers",
            ),
        ),
        migrations.AddField(
            model_name="genieapprovedquestions",
            name="company_id",
            field=models.ForeignKey(
                db_column="company_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.geniecompanies",
            ),
        ),
        migrations.AddField(
            model_name="genieapikeys",
            name="company_id",
            field=models.ForeignKey(
                db_column="company_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.geniecompanies",
            ),
        ),
        migrations.AddField(
            model_name="genieapikeys",
            name="genie_users_id",
            field=models.ForeignKey(
                db_column="genie_users_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="genie.genieusers",
            ),
        ),
        migrations.AddIndex(
            model_name="genieuserspayments",
            index=models.Index(
                fields=["genie_users_id"], name="genie_users_genie_u_f1e067_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genieuserspayments",
            unique_together={("genie_users_id", "client_secret", "payment_intent")},
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnectiondetailsdescription",
            index=models.Index(
                fields=[
                    "company_id",
                    "table_name",
                    "db_schema",
                    "db_warehouse",
                    "resourcename",
                    "column_name",
                ],
                name="genie_users_company_351618_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnectiondetailsdescription",
            index=models.Index(
                fields=[
                    "company_id",
                    "table_name",
                    "db_schema",
                    "db_warehouse",
                    "resourcename",
                ],
                name="genie_users_company_1973f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnectiondetailsdescription",
            index=models.Index(
                fields=["company_id", "table_name", "resourcename"],
                name="genie_users_company_77fd6f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genieusersdatabaseconnectiondetailsdescription",
            unique_together={
                (
                    "table_name",
                    "db_schema",
                    "db_warehouse",
                    "resourcename",
                    "company_id",
                    "column_name",
                )
            },
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnectiondetails",
            index=models.Index(
                fields=[
                    "company_id",
                    "table_name",
                    "db_schema",
                    "db_warehouse",
                    "resourcename",
                ],
                name="genie_users_company_243b97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnectiondetails",
            index=models.Index(
                fields=["company_id", "table_name", "resourcename"],
                name="genie_users_company_48373b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genieusersdatabaseconnectiondetails",
            unique_together={
                (
                    "company_id",
                    "table_name",
                    "db_schema",
                    "db_warehouse",
                    "resourcename",
                )
            },
        ),
        migrations.AddIndex(
            model_name="genieusersdatabaseconnection",
            index=models.Index(
                fields=["genie_users_id"], name="genie_users_genie_u_a01605_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genieusersdatabaseconnection",
            unique_together={("genie_users_id", "name", "resourcename")},
        ),
        migrations.AddIndex(
            model_name="genieusers",
            index=models.Index(
                fields=["username"], name="genie_users_usernam_15f548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genieuserloginmagiclinks",
            index=models.Index(fields=["email"], name="genie_user__email_7bc8d7_idx"),
        ),
        migrations.AddIndex(
            model_name="genieuserloginmagiclinks",
            index=models.Index(
                fields=["secret_code"], name="genie_user__secret__decceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genieuserinvitations",
            index=models.Index(fields=["email"], name="genie_user__email_640631_idx"),
        ),
        migrations.AddIndex(
            model_name="genieuserinvitations",
            index=models.Index(
                fields=["secret_code"], name="genie_user__secret__b3229c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geniechathistory",
            index=models.Index(
                fields=["datetime"], name="genie_chat__datetim_ed2989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geniechathistory",
            index=models.Index(
                fields=["genie_users_id"], name="genie_chat__genie_u_840ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geniechathistory",
            index=models.Index(
                fields=["genie_users_id", "datetime"],
                name="genie_chat__genie_u_aab3b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geniechathistory",
            index=models.Index(
                fields=["genie_users_id", "user_id_slack", "datetime"],
                name="genie_chat__genie_u_96c63c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geniechathistory",
            index=models.Index(
                fields=[
                    "company_id",
                    "resourcename",
                    "user_id_slack",
                    "team_id_slack",
                    "genie_users_id",
                ],
                name="genie_chat__company_78c5ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genieapprovedquestions",
            index=models.Index(
                fields=["datetime"], name="genie_appro_datetim_19f989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genieapprovedquestions",
            index=models.Index(
                fields=["company_id", "datetime"], name="genie_appro_company_5a724c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genieapikeys",
            index=models.Index(
                fields=["key_hash"], name="genie_api_k_key_has_92d29d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genieapikeys",
            index=models.Index(
                fields=["genie_users_id"], name="genie_api_k_genie_u_da96af_idx"
            ),
        ),
    ]
